from __future__ import annotations

from typing import Dict


VOICE_PERSONAS: Dict[str, Dict[str, str | float]] = {
    "female_warm_indian": {
        "gender": "female",
        "accent": "indian",
        "language": "en-IN",
        "tone": "warm_polite",
        "speaking_speed": 1.0,
        "pitch": 1.0,
        "greeting_style": "welcoming receptionist",
        "escalation_style": "calm and urgent",
        "fallback_style": "helpful and clear",
    },
    "female_professional_global": {
        "gender": "female",
        "accent": "global",
        "language": "en",
        "tone": "professional",
        "speaking_speed": 1.0,
        "pitch": 1.0,
        "greeting_style": "enterprise formal",
        "escalation_style": "composed and direct",
        "fallback_style": "neutral support",
    },
    "female_hindi_friendly": {
        "gender": "female",
        "accent": "indian",
        "language": "hi-en",
        "tone": "friendly bilingual",
        "speaking_speed": 0.98,
        "pitch": 1.02,
        "greeting_style": "Hindi-English friendly",
        "escalation_style": "empathetic bilingual",
        "fallback_style": "simple bilingual guidance",
    },
    "female_south_indian_english": {
        "gender": "female",
        "accent": "south-indian",
        "language": "en-IN",
        "tone": "clear",
        "speaking_speed": 1.0,
        "pitch": 1.0,
        "greeting_style": "clear concise receptionist",
        "escalation_style": "steady and calm",
        "fallback_style": "clarity-first guidance",
    },
    "female_empathetic": {
        "gender": "female",
        "accent": "global",
        "language": "en",
        "tone": "empathetic",
        "speaking_speed": 0.92,
        "pitch": 0.98,
        "greeting_style": "gentle reassurance",
        "escalation_style": "compassionate urgent",
        "fallback_style": "soft clarification",
    },
    "male_professional_indian": {
        "gender": "male",
        "accent": "indian",
        "language": "en-IN",
        "tone": "professional",
        "speaking_speed": 1.0,
        "pitch": 0.95,
        "greeting_style": "formal desk tone",
        "escalation_style": "firm calm urgency",
        "fallback_style": "structured guidance",
    },
    "male_calm_global": {
        "gender": "male",
        "accent": "global",
        "language": "en",
        "tone": "calm",
        "speaking_speed": 0.96,
        "pitch": 0.95,
        "greeting_style": "calm neutral",
        "escalation_style": "steady clear urgency",
        "fallback_style": "patient explanation",
    },
    "male_hindi_friendly": {
        "gender": "male",
        "accent": "indian",
        "language": "hi-en",
        "tone": "friendly bilingual",
        "speaking_speed": 1.0,
        "pitch": 0.97,
        "greeting_style": "Hindi-English welcoming",
        "escalation_style": "calm bilingual urgency",
        "fallback_style": "easy bilingual fallback",
    },
    "male_fast_reception": {
        "gender": "male",
        "accent": "indian",
        "language": "en-IN",
        "tone": "fast operational",
        "speaking_speed": 1.08,
        "pitch": 0.95,
        "greeting_style": "quick desk greeting",
        "escalation_style": "direct triage tone",
        "fallback_style": "short and actionable",
    },
    "male_deep_trust": {
        "gender": "male",
        "accent": "global",
        "language": "en",
        "tone": "deep reassuring",
        "speaking_speed": 0.94,
        "pitch": 0.9,
        "greeting_style": "reassuring intro",
        "escalation_style": "grounded confidence",
        "fallback_style": "trust-building clarity",
    },
}


def get_persona(persona_id: str) -> Dict[str, str | float]:
    return VOICE_PERSONAS.get(persona_id, VOICE_PERSONAS["female_warm_indian"])
